config/routes.rb
Rails.application.routes.draw do
  get 'andlikes/index'

  get 'andlikes/show'

  get 'andlikes/new'

  get 'andlikes/edit'

  get 'andusers/index'

  get 'andusers/show'

  get 'andusers/new'

  get 'andusers/edit'

  get 'likes/index'

  root 'home#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  get 'home/index'

Rails.application.routes.draw do
  get 'andlikes/index'

  get 'andlikes/show'

  get 'andlikes/new'

  get 'andlikes/edit'

  get 'andusers/index'

  get 'andusers/show'

  get 'andusers/new'

  get 'andusers/edit'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  get 'home/index'

  root 'home#index'
end

  get 'andrecipes/index'

  get 'andrecipes/show'

  post 'andrecipes/new'

  get 'andrecipes/edit'

  resources :recipes do

        resources :likes
        
  	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
mount_uploader :image, ImageUploader
has_many :likes, dependent: :destroy
belongs_to :user, foreign_key: 'recipe_id'


scope :recent, ->{where('created_at <= :a', a: Time.now - 2.minutes)}    
   
    
    #scope :recent, ->{joins(:user).where('recipes.created_at + "remainingTime" = :a', a:Time.now)}
    #scope :recent, ->{joins(:user).where('created_at <= :a', a: Time.now - remainingTime.Minutes)}    


    def self.searchTag(searchTag)

        if searchTag
           recipe2 = Recipe.where(:recipe_tags => searchTag)

            if recipe2
                self.where(id: recipe2)

            end

            else
                Recipe.all
        end
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :current_recipe, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
  def index
     @recipes = Recipe.searchTag(params[:searchTag])
  end

  def show
    puts @recipe.image
  end

  def new
    if current_user
      @recipe = Recipe.new
      @recipe.recipe_id = current_user.id
      
    else
      @recipe = Recipe.new
    end
 
    
  end

  def create
    recipe = Recipe.create(recipe_params)
    redirect_to recipe_path(recipe)
  end

  def edit

  end

  def update
    @recipe.update(recipe_params)

    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe.destroy

    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:recipe_name, :recipe_detail, :recipe_ingredients, :recipe_tags, :search, :recipe_id, :image, :image_cache)
  end

  def current_recipe
    @recipe = Recipe.find(params[:id])
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<!doctype html>
<html lang="en">
  <head>

    <title>Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
            <a class="navbar-brand" >
                <%=link_to 'Home Page',"/recipes/",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" >
              <%=link_to 'Add Recipe',"/recipes/new",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>


            <a class="navbarbtn" >


            <%= form_tag(recipes_path,method: :get) do%>
            <%= text_field_tag(:searchTag, params[:searchTag],{:style=>'background-color:white;border-color:black;height:30px;width:200px'})%>
            <%= submit_tag ("Search Tag"),{:style=>'background-color:white;border-color:black;text-color:black;font:bold 15px arial;margin-top:5px'}%>
            <% end %>

            <style>
              .navbarbtn{
                  position:absolute;
                  right:40px;

               }
            </style>
            </a>

          </nav>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>

  <div class="carousel-item active">
                <%= image_tag("update.jpg", :style => 'z-index: -1;background-position: center right;')%>
  </div>
</body>

<body>


<div class="container">

      <%= form_with model: @recipe do |form| %>
     <div class="form-row">
    <div class="col-sm-4">
      <h3><strong>Recipe Name

        <style>
         h3{
           color:white;
         }
         </style> </strong></h3>
       <%= form.text_field :recipe_name, placeholder: "Recipe Name",:style => 'width:200px;height:100px' %>
    </div>

    <div class="col-sm-4">
      <h3>Ingredients</h3>
      <%= form.text_field :recipe_ingredients, placeholder: "Ingredients",:style => 'width:200px;height:100px' %>
    </div>
    </div>
    <div class="form-row">
    <div class="col-sm-4">
      <h3>Detail</h3>
       <%= form.text_field :recipe_detail, placeholder: "Detail",:style => 'width:200px;height:100px' %>
    </div>

    <div class="col-sm-4">
      <h3>Tags</h3>
      <%= form.text_field :recipe_tags, placeholder: "Tags" ,:style => 'width:200px;height:100px'%>
    </div>
    <div class="col-sm-4">
      <h3>Image</h3>
      <% if form.object.image? %>
      <%= image_tag(@recipe.image.url, alt:'Image',:style=>'height: auto;width: auto;max-width: 300px;max-height: 300px;' )if @recipe.image?%>
      <%= form.file_field :image %>
      <% else %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
      <% end %>

    </div>
      <%= form.submit :style => 'width:170px;height:40px;font:bold 15px arial;background-color:white;position:absolute;right:285px;left:285px;bottom:50px'%>
    <% end %>
    <style>
      .container{
        position: absolute;

                   left:400px;
                   padding: 120px;
                   right: 10px;
                   bottom:20px;
        z-index:10000000000;

      }
    </style>
</div>

</body>
</html>

app/views/recipes/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">


            <a class="navbar-brand" >
              <%=link_to 'Home Page',"/recipes/",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" >
              <%=link_to 'Add Recipe',"/recipes/new",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>
             <a class="navbar-brand" >
              <%=link_to 'LogOut Page',"/home/index",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>
            <a class="navbarbtn" >


            <%= form_tag(recipes_path,method: :get) do%>
            <%= text_field_tag(:searchTag, params[:searchTag],{:style=>'background-color:white;border-color:black;height:30px;width:200px'})%>
            <%= submit_tag ("Search Tag"),{:style=>'background-color:white;border-color:black;text-color:black;font:bold 15px arial;margin-top:5px'}%>
            <% end %>

            <style>
              .navbarbtn{
                  position:absolute;
                  right:40px;

               }
            </style>
            </a>
      </nav>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>


  <body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
  <body>
        <div class="carousel-item active">
          <%= image_tag("table.jpg", :style => 'z-index: -1;background-size: cover;
background-position: center;
background-repeat: no-repeat;
height: 100%;')%>
            <%# <img src="img/table.jpg" class="img-fluid" alt="Responsive image"> %>
        </div>
        <div class="text-block">
            <style>.container {
                    position: relative;
                  }

                  /* Bottom right text */
                  .text-block {
                    position:relative;
                    align:center;
                    bottom:200px;
                    top:200px;
                    height: 300px;
                    color: white;
                    padding-left: 200px;
                    padding-right: 200px;

                  }
            </style>
                <h6><strong>Delicious food area
                    <style>
                        h6{
                            position:relative;
                            font-size: 40px;
                        }

                    </style>
                </strong></h6>
                <h5>
                        <style>
                                h5{
                                    font-size: 20px;
                                }

                        </style>
                          <ul>
                          <% @recipes.each do |recipe| %>
                            <li><%= link_to recipe.recipe_name,recipe_path(recipe) ,{:style=>'color:#FFFFFF;', :class => "css_class"}%></li>
                            <p><%= recipe.likes.count %> <%= (recipe.likes.count) == 1 ? 'Like' : 'Likes'%></p>

                          <% end %>
                        </ul>
                </h5>
        </div>
  </body>

</html>

app/views/recipes/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
            <a class="navbar-brand" >
              <%=link_to 'Home Page',"/recipes/",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" >
              <%=link_to 'Add Recipe',"/recipes/new",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>

            <a class="navbarbtn" >


            <%= form_tag(recipes_path,method: :get) do%>
            <%= text_field_tag(:searchTag, params[:searchTag],{:style=>'background-color:white;border-color:black;height:30px;width:200px'})%>
            <%= submit_tag ("Search Tag"),{:style=>'background-color:white;border-color:black;text-color:black;font:bold 15px arial;margin-top:5px'}%>
            <% end %>

            <style>
              .navbarbtn{
                  position:absolute;
                  right:40px;

               }
            </style>
            </a>

          </nav>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
  <body>




        <div class="carousel-item active">
                <%= image_tag("spices.jpg", :style => 'z-index: -1;')%>
         </div>

        <div class= "needs-validation">
          <h3> Let's share your recipe with us !</h3>

            <%= form_with model: @recipe do |form| %>
          <%# <form class="needs-validation" novalidate> %>
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <%= form.text_field :recipe_name, placeholder: "Recipe Name" %>
                    <%# <label for="validationTooltip01">Recipe Name</label> %>
                    <%# <input type="text" class="form-control" id="validationTooltip01"  placeholder="First name" value="Pancake" required> %>
                    <div class="valid-tooltip">
                      Looks good!
                    </div>
                  </div>
                </div>
                  <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <%= form.text_field :recipe_detail, placeholder: "Detail" %>
                    <%# <label for="validationTooltip02">Recipe Details</label> %>
                    <%# <input type="text" class="form-control" id="validationTooltip02" placeholder="Last name" value="Take a cup,break egg into the cup..." required> %>
                    <div class="valid-tooltip">
                      Looks good!
                    </div>
                  </div>
                </div>

                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <%= form.text_field :recipe_tags, placeholder: "Tags" %>

                    <%# <label for="validationTooltip02">Recipe Details</label> %>
                    <%# <input type="text" class="form-control" id="validationTooltip02" placeholder="Last name" value="Take a cup,break egg into the cup..." required> %>
                    <div class="valid-tooltip">
                      Looks good!
                    </div>
                  </div>
                </div>
                    <%= form.hidden_field :recipe_id %>
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <%= form.text_field :recipe_ingredients, placeholder: "Ingredients" %>
                    <%# <label for="validationTooltip03">Ingredients</label> %>
                    <%# <input type="text" class="form-control" id="validationTooltip03" placeholder="Olive oil,potata..." required> %>
                    <div class="invalid-tooltip">
                      Please provide a valid city.
                    </div>
                </div>
                </div>
                <div class=container>
                <div class="form-row">
                <div class="col-md-4 mb-3">
                        <form action="/action_page.php">
                            <%# <input type= "file" name="pic" accept="image/*"> %>
                            <%= form.file_field :image, placeholder: "Image" %>
                            <!-- <input type="submit"> -->
                          </form>
                  </div>
                </div>
              <div class=container>
                <div class="form-row">
                <div class="col-md-4 mb-3">
                  </div>
                </div>



                <style>

                .container {
                    position: relative;
                  }

                  input[type=text]{
                    width: 400px;
                    height: 100px;

                }

                </style>
                <style>
                .needs-validation{
                    align:center;
                    position:absolute;
                    bottom:200px;
                    top:200px;
                    right:500px;
                    left:500px;
                    height: 300px;
                    color: white;
                    padding-left: 50px;
                    padding-right: 50px;

                }
                </style>

             <%= form.submit :style => 'width:170px;height:40px;font:bold 15px arial;background-color:white;position:absolute;right:120px;left:120px' %>
            <% end %>
            </div>
            </div>


  </body>

</html>

app/views/recipes/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
            <a class="navbar-brand" >
                <%=link_to 'Home Page',"/recipes/",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" >
              <%=link_to 'Add Recipe',"/recipes/new",{:style=>'color:#FFFFFF;border-style:solid;width:100px;text-align:center', :class => "css_class"}%>
            </a>

            <a class="navbarbtn" >


            <%= form_tag(recipes_path,method: :get) do%>
            <%= text_field_tag(:searchTag, params[:searchTag],{:style=>'background-color:white;border-color:black;height:30px;width:200px'})%>
            <%= submit_tag ("Search Tag"),{:style=>'background-color:white;border-color:black;text-color:black;font:bold 15px arial;margin-top:5px'}%>
            <% end %>

            <style>
              .navbarbtn{
                  position:absolute;
                  right:40px;

               }
            </style>
            </a>

          </nav>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <div class="carousel-item active">
                  <%= image_tag("odun.jpg", :style => 'z-index: -1;background-position: center right;')%>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>

    <body>

  <div class="card" style="width: 50rem; position: absolute;
                    background-color:white;
                    bottom:200px;
                    top:200px;
                    right: 350px;
                    resize: both;
                    overflow: auto;
                    height: 600px;">

     <h5 class="card-header"><strong><%= @recipe.recipe_name %></strong></h5>
      <div class="card-body">
      <p><%= @recipe.likes.count %> <%= (@recipe.likes.count) == 1 ? 'Like' : 'Likes'%></p>
      <%= button_to 'Like', recipe_likes_path(@recipe), method: :recipe %>
      <div><%= notice %></div>
        <h5 class="card-title "><strong>Ingredients:</strong> </h5>
         <%= @recipe.recipe_ingredients %>
         <br>

            <%= image_tag(@recipe.image.url, alt:'Image',:style=>'height: auto;width: auto;max-width: 300px;max-height: 300px;' ) if @recipe.image?%>
          <br>
         <br>
          <h5 class="card-text"><strong>How to make ?</strong><br></h5>
          <%= @recipe.recipe_detail %>
          <br>
          <br>
          <h5 class= "card-text"><strong> Tags :</strong> </h5>
          <%= @recipe.recipe_tags %>
          <br>
          <br>
          <h5 class= "card-text"><strong> Recipe created by :</strong> </h5>
          <%= User.find(@recipe.recipe_id).nickname%>
          <br>
          <br>
          <div class=rm>
          <%= link_to 'Remove' , recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure delete this recipe?' } %>
          <%=link_to 'Edit  ',{:action => "edit", :controller => "recipes", :anchor => "id" }%>


          </div>
          <br>
          <style>
              .card-header {
                  background-color: black;
                  color:white;
              }
          </style>
  </div>
</div>

  </body>

</html>