config/routes.rb
Rails.application.routes.draw do
  get 'andlikes/index'

  get 'andlikes/show'

  get 'andlikes/new'

  get 'andlikes/edit'

  get 'andusers/index'

  get 'andusers/show'

  get 'andusers/new'

  get 'andusers/edit'

  get 'likes/index'

  root 'home#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
 

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  get 'home/index'

Rails.application.routes.draw do
  get 'andlikes/index'

  get 'andlikes/show'

  get 'andlikes/new'

  get 'andlikes/edit'

  get 'andusers/index'

  get 'andusers/show'

  get 'andusers/new'

  get 'andusers/edit'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  get 'home/index'

  root 'home#index'
end

  get 'andrecipes/index'

  get 'andrecipes/show'

  post 'andrecipes/new'

  get 'andrecipes/edit'

  resources :recipes do

        resources :likes
        
  	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" href="style.css">
    </head>
<body>
<div class="tasi">
<h1 style="color:#ffd9b3;font-size:100px;font-family:Bradley Hand ITC;font-weight: bold">RESISIPE</h1>

<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path ,{:style=>'background-color:white;border-color:black;text-color:black;font:bold 30px Bradley Hand ITC;margin-top:5px'}%>
<% else %>
  <%= link_to "Sign Up", signup_path,{:style=>'background-color:white;border-color:black;text-color:black;font:bold 30px Bradley Hand ITC;margin-top:5px'} %> 
  <a style='color:#ccf2ff; font:bold 30px Bradley Hand ITC;' >or</a>
  <%= link_to "Log In", login_path ,{:style=>'background-color:white;border-color:black;text-color:black;font:bold 30px Bradley Hand ITC;margin-top:5px'} %>
<% end %>
<p id="notice" ><%= notice %></p>
<%= link_to "See All Recipes", recipes_path ,{:style=>'background-color:white;border-color:black;text-color:black;font:bold 30px Bradley Hand ITC;margin-top:5px'} %>
</div>

</body>

</html>
<style>
html,body{
background-image: url('https://cdn.pixabay.com/photo/2019/04/05/09/41/table-4104652_1280.jpg');
background-size: cover;
background-position: center; 
background-repeat: no-repeat;
height: 100%;
font-family: 'Numans', sans-serif;
}
.tasi{
  position:relative;
  right:500px;
  left:600px;
  bottom:500px;
  top:300px;
}
</style>